AWSTemplateFormatVersion: "2010-09-09"
Description: "Preview Deployment: Simple S3 Static Website"

Parameters:
  SiteBucketName:
    Type: String
    Description: "Name for the S3 bucket for static website"

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SiteBucketName
      WebsiteConfiguration:
        IndexDocument: "index.html"
    DeletionPolicy: Delete

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${SiteBucket.Arn}/*"

Outputs:
  WebsiteURL:
    Description: "S3 Website URL"
    Value: !GetAtt SiteBucket.WebsiteURL
